### ISSUE TITLE
IP validator for common 

### ISSUE THREAD

**Issue by JakeRoggenbuck** [jabacat/rclc#26]

**Comment by adamhutchings** [comment]
Why do we need it in `common/`?

**Comment by JakeRoggenbuck** [comment]
So that client server & client can both use it. The client will only let you send a request to the server with an actual IP to reduce spam, give user helpful validation in the client (if they make a mistake), and reduce attack vector size. Then, if a fake request is made from something other than an official client, the server will complain about it instead of storing it as well.

**Comment by jacobhenn** [comment]
what do you mean by "actual ip"

**Comment by JakeRoggenbuck** [comment]
```rs
check_ip("192.168.5.1"); // Good - maybe says "Is local" as well
check_ip("45.1.34"); // No Good
check_ip("hello world"); // No Good
check_ip("23.345.65.340"); // No Good
```

**Comment by JakeRoggenbuck** [comment]
```rs
check_ip("35.43.154.76"); // Good
```

**Comment by jacobhenn** [comment]
`Message` contains a `std::net::IpAddr`, whose `FromStr` method should handle that for us

**Comment by JakeRoggenbuck** [comment]
Ayy! nice, that's good to know

**Comment by JakeRoggenbuck** [comment]
I love high level libraries

**Comment by adamhutchings** [comment]
Should we close this issue then?

**Comment by JakeRoggenbuck** [comment]
Now all we have to do is give good user error messages on the client

**Comment by JakeRoggenbuck** [comment]
> Should we close this issue then?

yea

**Comment by jacobhenn** [comment]
> Now all we have to do is give good user error messages on the client

that should be a breeze with `anyhow`. i'm working on the client, and i will do my best to have error messages of the highest quality.

**Comment by JakeRoggenbuck** [comment]
ayy, thanks!
